services:
    concerto_cms_core.pages.controller.pages:
        class: ConcertoCms\CoreBundle\Pages\Controller\PagesController
        arguments:
            - @concerto_cms_core.pages.service.pages_manager

