services:
    concerto_cms_core.pages.service.pages_manager:
        class: ConcertoCms\CoreBundle\Pages\Service\PagesManager
        arguments:
            - @doctrine_phpcr.odm.default_document_manager
