concerto_cms_core_dashboard:
    pattern:  /
    defaults: { _controller: ConcertoCmsCoreBundle:Default:index }

concerto_cms_core_content:
    pattern:  /content
    defaults: { _controller: ConcertoCmsCoreBundle:Content:index }

concerto_cms_core_content_rest:
    pattern:  /rest/content
    defaults: { _controller: ConcertoCmsCoreBundle:Content:getPages }
    methods:  [GET]
    options:
        expose: true

concerto_cms_core_content_rest_post:
    pattern:  /rest/content
    defaults: { _controller: ConcertoCmsCoreBundle:Content:postPage }
    methods:  [POST]

concerto_cms_core_content_rest_put:
    pattern:  /rest/content/{id}
    defaults: { _controller: ConcertoCmsCoreBundle:Content:putPage }
    methods:  [PUT]

