#concerto_cms_core_dashboard:
#    pattern:  /
#    defaults: { _controller: ConcertoCmsCoreBundle:Default:index }

########################################################################
#  Content
########################################################################
#concerto_cms_core_content:
#    pattern:  /content
#    defaults: { _controller: ConcertoCmsCoreBundle:Content:index }

concerto_cms_core_content_rest:
    pattern:  /rest/content/{path}
    defaults: { _controller: ConcertoCmsCoreBundle:Content:getPage, path: null }
    methods:  [GET]
    requirements:
        path: .+
    options:
        expose: true

concerto_cms_core_content_rest_post:
    pattern:  /rest/content/{path}
    defaults: { _controller: ConcertoCmsCoreBundle:Content:postPage }
    methods:  [POST]
    requirements:
        path: .+

concerto_cms_core_content_rest_put:
    pattern:  /rest/content/{path}
    defaults: { _controller: ConcertoCmsCoreBundle:Content:putPage }
    methods:  [PUT]
    requirements:
        path: .+

concerto_cms_core_content_rest_delete:
    pattern:  /rest/content/{path}
    defaults: { _controller: ConcertoCmsCoreBundle:Content:deletePage }
    methods:  [DELETE]
    requirements:
        path: .+

########################################################################
#  Navigation
########################################################################
#concerto_cms_core_navigation:
#    pattern:  /navigation
#    defaults: { _controller: ConcertoCmsCoreBundle:Navigation:index }

########################################################################
#  Media
########################################################################
concerto_cms_core_media:
    pattern:  /media
    defaults: { _controller: ConcertoCmsCoreBundle:Media:index }
