parameters:
#    concerto_cms_core.example.class: ConcertoCms\CoreBundle\Example

services:
    concerto_cms_core.phpcr.initializer:
        class: Doctrine\Bundle\PHPCRBundle\Initializer\GenericInitializer
        arguments:
            - [ "/cms", "/cms/pages" ]
        tags:
            - { name: doctrine_phpcr.initializer }
    concerto_cms_core.contentmanager:
        class: ConcertoCms\CoreBundle\Service\Content
        arguments:
            - [ doctrine_phpcr.odm.default_document_manager ]
