parameters:
#    concerto_cms_core.example.class: ConcertoCms\CoreBundle\Example

services:
    concerto_cms_core.phpcr.initializer:
        class: Doctrine\Bundle\PHPCRBundle\Initializer\GenericInitializer
        arguments:
            - [ "/cms", "/cms/pages", "/cms/media", "/cms/media/shared" ]
        tags:
            - { name: doctrine_phpcr.initializer }
    concerto_cms_core.initializer:
        class: ConcertoCms\CoreBundle\Service\Initializer
        arguments:
            - @concerto_cms_core.content
        tags:
            - { name: doctrine_phpcr.initializer }
    concerto_cms_core.content:
        class: ConcertoCms\CoreBundle\Service\Content
        arguments:
            - @doctrine_phpcr.odm.default_document_manager
            - @event_dispatcher
    concerto_cms_core.repository.page:
        class: ConcertoCms\CoreBundle\Repository\Page
        arguments:
            - @doctrine_phpcr.odm.default_document_manager
            - @event_dispatcher
        tags:
            - { name: concerto.repository }
    concerto_cms_core.navigation:
        class: ConcertoCms\CoreBundle\Service\Navigation
        arguments:
            - @doctrine_phpcr.odm.default_document_manager
        tags:
            - name: kernel.event_listener
              event: concerto.language.add
              method: onLanguageAdd
    concerto_cms_core.extension_container:
        class: ConcertoCms\CoreBundle\Extension\ExtensionContainer
        arguments:
            - @knp_menu.factory
    concerto_cms_core.extension:
        class: ConcertoCms\CoreBundle\Service\Extension
        tags:
            - { name: concerto.extension }
    concerto_cms_core.menu.topmenu:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: concerto_cms_core.extension_container
        factory_method: buildTopMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: topmenu } # The alias is what is used to retrieve the menu
    concerto_cms_core.twig.content_extension:
        class: ConcertoCms\CoreBundle\Twig\ContentExtension
        arguments: ["@concerto_cms_core.content"]
        tags:
            - { name: twig.extension }
