parameters:
#    concerto_cms_core.example.class: ConcertoCms\CoreBundle\Example

services:
    concerto_cms_core.phpcr.initializer:
        class: Doctrine\Bundle\PHPCRBundle\Initializer\GenericInitializer
        arguments:
            - concerto_cms_core.phpcr.initializer
            - [ "/cms", "/cms/pages", "/cms/media", "/cms/media/shared" ]
        tags:
            - { name: doctrine_phpcr.initializer }
    concerto_cms_core.pagemanager_container:
        class: ConcertoCms\CoreBundle\Extension\PageManagerContainer
        arguments:
            - @event_dispatcher

    concerto_cms_core.navigation:
        class: ConcertoCms\CoreBundle\Service\Navigation
        arguments:
            - @doctrine_phpcr.odm.default_document_manager
        tags:
            - name: kernel.event_listener
              event: concerto.language.add
              method: onLanguageAdd

    concerto_cms_core.content:
        class: ConcertoCms\CoreBundle\Service\Content
        arguments:
            - @doctrine_phpcr.odm.default_document_manager
            - @event_dispatcher
            - @concerto_cms_core.pagemanager_container

    concerto_cms_core.manager.page:
        class: ConcertoCms\CoreBundle\Service\PageManager
        tags:
            - { name: concerto.pagemanager }

    concerto_cms_core.mainmenu.builder:
        class: ConcertoCms\CoreBundle\Menu\MainMenuBuilder
        arguments:
            - @event_dispatcher
            - @knp_menu.factory
    concerto_cms_core.mainmenu.provider:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: concerto_cms_core.mainmenu.builder
        factory_method: build
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: topmenu } # The alias is what is used to retrieve the menu
    concerto_cms_core.extension.mainmenu:
        class: ConcertoCms\CoreBundle\Extension\MainMenuListener
        tags:
            - name: kernel.event_listener
              event: concerto.menu.main.build
              method: onBuild

    concerto_cms_core.twig.content_extension:
        class: ConcertoCms\CoreBundle\Twig\ContentExtension
        arguments: ["@concerto_cms_core.pagemanager_container"]
        tags:
            - { name: twig.extension }

