parameters:
#    concerto_cms_core.example.class: ConcertoCms\CoreBundle\Example

services:
#    concerto_cms_core.example:
#        class: %concerto_cms_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
