parameters:
#    concerto_cms_core.example.class: ConcertoCms\CoreBundle\Example

imports:
    - { resource: Pages/services.yml }
    - { resource: Pages/controllers.yml }

services:
    concerto_cms_core.phpcr.initializer:
        class: Doctrine\Bundle\PHPCRBundle\Initializer\GenericInitializer
        arguments:
            - concerto_cms_core.phpcr.initializer
            - [ "/cms", "/cms/pages", "/cms/media", "/cms/media/shared" ]
        tags:
            - { name: doctrine_phpcr.initializer }


