language: php

php:
  - 5.5
  - 5.4

before_install:
  - npm install -g grunt-cli
  - npm install
  - pear install PHP_CodeSniffer
  - composer install

before_script:
  - phpenv rehash

script:
  - phpcs --report=summary --ignore=Resources/public/* --extensions=php --standard=PSR2 .
  - grunt test
  - phpunit
