language: php

php:
  - 5.5
  - 5.4

before_script:
  - pear install PHP_CodeSniffer
#  - chmod a+x .travis.sh

#script: ./.travis.sh

script:
  - phpcs --report=summary --standard=PSR2 .
