language: php

php:
  - 5.5
  - 5.4
  - 5.6

before_install:
  - pear install PHP_CodeSniffer
  - composer install

before_script:
  - phpenv rehash

script:
  - phpcs --ignore=vendor/* --extensions=php --standard=PSR2 .
  - phpunit
