language: php

php:
  - 5.5
  - 5.4

before_install:
  - pear install PHP_CodeSniffer
  - composer install

before_script:
  - phpenv rehash

script:
  - phpcs --report=summary --ignore=Resources/public/*,vendor/* --extensions=php --standard=PSR2 .
  - phpunit
