language: php

php:
  - 5.5
  - 5.4

before_script:
  - pear install PHP_CodeSniffer
  - pear install pear.phing.info/phing

script: phing

#script:
#  - phpcs --report=summary --standard=PSR2 .
