services:
    concerto_cms_core.navigation.controller.navigation:
        class: ConcertoCms\CoreBundle\Navigation\Controller\NavigationController
        arguments:
            - @concerto_cms_core.navigation.service.navigation_manager