concerto_cms_core_navigation_rest:
    pattern:  /navigation/{path}
    defaults: { _controller: concerto_cms_core.navigation.controller.navigation:listAction, path: null }
    methods:  [GET]
    requirements:
        path: .+
    options:
        expose: true

concerto_cms_core_navigation_rest_post:
    pattern:  /navigation/{path}
    defaults: { _controller: concerto_cms_core.navigation.controller.navigation:postAction }
    methods:  [POST]
    requirements:
        path: .+

concerto_cms_core_navigation_rest_put:
    pattern:  /navigation/{path}
    defaults: { _controller: concerto_cms_core.navigation.controller.navigation:putAction }
    methods:  [PUT]
    requirements:
        path: .+

concerto_cms_core_navigation_rest_delete:
    pattern:  /navigation/{path}
    defaults: { _controller: concerto_cms_core.navigation.controller.navigation:deleteAction }
    methods:  [DELETE]
    requirements:
        path: .+
