services:
    concerto_cms_core.navigation.controller:
        class: ConcertoCms\CoreBundle\Navigation\Controller\NavigationController
        arguments:
        arguments:
            - @concerto_cms_core.navigation.navigationmanager