concerto_cms_core_languages_rest:
    pattern:  /languages
    defaults: { _controller: concerto_cms_core.languages.controller.languages:listAction }
    methods:  [GET]
    options:
        expose: true

concerto_cms_core_languages_rest_get:
    pattern:  /languages/{path}
    defaults: { _controller: concerto_cms_core.languages.controller.languages:getAction }
    methods:  [GET]
    options:
        expose: true

concerto_cms_core_languages_rest_post:
    pattern:  /languages
    defaults: { _controller: concerto_cms_core.languages.controller.languages:postAction }
    methods:  [POST]

concerto_cms_core_languages_rest_put:
    pattern:  /languages/{path}
    defaults: { _controller: concerto_cms_core.languages.controller.languages:putAction }
    methods:  [PUT]

concerto_cms_core_languages_rest_delete:
    pattern:  /languages/{path}
    defaults: { _controller: concerto_cms_core.languages.controller.languages:deleteAction }
    methods:  [DELETE]
